### PR TITLE
E043 message fix

### PR DESCRIPTION
**Pull request by dangreen**

### CODE REVIEW

**Comment by dangreen** [comment]
@mlochbaum hey?

**Comment by mlochbaum** [comment]
I changed the rule rather than the error message, since I think `previous` should come before `attribute` in the html being linted. I also caught a few other incorrectly formatted messages. I plan on better integrating the messages into htmllint, and possibly adding some tests for them.

**Comment by dangreen** [comment]
@mlochbaum can you update package on npm with this fix?

**Comment by dangreen** [comment]
@mlochbaum ?

**Pull request closed without merging**
