### PR TITLE
class no dup

### PR DESCRIPTION
**Pull request by mfong**

### CODE REVIEW

**Comment by mlochbaum** [comment]
The `class-no-dup` patch looks good, and I can accept it now. However, I don't want to accept `img-req-dimensions` right now for the reasons discussed below. Can you separate `class-no-dup` out and pull request it separately? I can do it on this end, but I think it will make the branch tree look very messy.

I had been thinking (silently, sorry) about the `img-req-dimensions` request before this. I'm hesitant to add it because I would like to write a more general option to specify that some tags must include nonempty attributes of a certain type. Then `img-req-dimensions` could be accomplished just by adding `{img: ['height', 'width']}` to that.

The problem with `height` and `width` not being allowed attributes (when they should be allowed, but only for `img`s) is also something I want to address in a cleaner way, but I'm not even sure what an appropriate interface for that would look like.

**Comment by mlochbaum** [comment]
Oh, and I do want to say that I'll make sure htmllint has the functionality of `img-req-dimensions` by the next release, either using your code or something more general.

**Comment by mfong** [comment]
np, I'll try and get it in tomorrow

**Comment by mlochbaum** [comment]
I haven't forgotten this, but the changes I mentioned should go in a major release. So there's a minor release now with some other bugfixes and added options, and the image height and width issue will be fixed soon.

**Pull request closed without merging**
