### PR TITLE
Feature/split id and class format

### PR DESCRIPTION
**Pull request by KrekkieD**
Allows separation between id and class format. This allows the popular [BEM-format](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/) for classes, while using a different rule for `id`s.

Also added a script in package.json for testing without global installs (`npm run testlocal`).

### CODE REVIEW

**Comment by mlochbaum** [comment]
I'm still considering this change. Because it breaks compatibility, and because most users will probably want to use the same format for ids and classes, it may be better to keep `id-class-style` and include a `class-style` option which overrides that for classes.

**Comment by KrekkieD** [comment]
I see your point with backwards compatibility. Maybe the best way would be to use `id-class-style` as a short-hand version to set both the `id-style` and `class-style` rules (if undefined).

The `id-style` rule actually shouldn't break on whitespace as the whitespace is officially part of the id value (not a separator as it is with classes). So instead of using `id-class-style` as a rule and having to check the current attribute tag name and changing logic based on id or class, it may be better to keep the rules separated, but allow a single config property to set both. That way we keep backwards compatibility  without over complicating the individual rule logic.

What do you think?

**Comment by mlochbaum** [comment]
The difference between how ids and classes are parsed is a good reason to keep them in separate rules but doesn't really constrain the way options are designed.

I think the concept of having a virtual option that really just sets other options is more complication than it's worth in terms of the user interface. I do agree that it's a slightly nicer interaction pattern for the user that knows how everything works, but if you don't know that `id-class-style` is a weird half-option thing then htmllint will appear to behave very strangely. We get a pretty similar interface by having two real options `id-class-style` and `class-style` but making the class checking rule fall back on `id-class-style` if `class-style` is false. The main difference is that if `class-style` is set, then you have to make it false before changing `id-class-style` in order to change both options. However, setting `class-style` already sort of indicates that you want the two to be treated differently, so I don't think that's a big problem.

It's possible that we would want to rename options, like changing `id-class-style` to `id-style` or `class-style` to `class-style-override`, with such a change. Neither of those seem too elegant, though.

**Comment by yvanavermaet** [comment]
You want to avoid breaking changes as much as possible, especially when upgrading the minor version.
Renaming a rule would break set-ups, so you'd have to increase the major version for it.

Imo, the best approach would be to keep "id-class-style", but deprecate it. Then create 2 new rules: id-style and class-style.
Once you have enough changes to upgrade the major version, you can remove the deprecated rules.

**Comment by mlochbaum** [comment]
Yes, I kind of contradicted myself in the last paragraph. I think it's better to just keep `id-class-style` and add `class-style`. It's asymmetric, but it has to be if we want to keep the ability to change both styles together.

**Comment by mlochbaum** [comment]
I've merged this pull request after applying my suggestion. Note that there are now two rules `id-style` and `class-style` which correspond in a skewed manner to the options `id-class-style` and `class-style`. I've also changed the `id-style` rule so that it doesn't split ids on spaces, in accordance with the html spec.

We can certainly keep discussing the best scheme for the options that control these rules. That part is pretty easy to change. This pull request pertains more to the architecture of the rules (which there is no disagreement about), so I felt it was appropriate to add it.

**Comment by KrekkieD** [comment]
Nice, looks pretty clean. Perhaps for `id-style` use the same rule value retrieval as used with `class-style`? i.e. `var format = opts[this.name] || opts['id-class-style'];`?

Also, any estimate on when the changes will be published to NPM? I'm currently including my github fork in a package, but now it seems I can use the actual htmllint package when it's published.

**Comment by mlochbaum** [comment]
I'm hesitant to add a third option to control these two rules since it makes deciding how to change the id rule more difficult. That is, you have to check whether `id-style` is set first. I am still considering both ways and would certainly change it in the future if users said it was a problem.

I've asked Michael to update npm. He should have that done in a day at most. At some point I should learn how to do this myself...

**Pull request merged**
