### PR TITLE
Add a custom separator option for `class-no-dup`

### LINKED ISSUE #157: `class-no-dup` is not very friendly with Angular interpolation
A class definition with Angular interpolated values won't work with `class-no-dup`, so I suggest we can configure it with some kind of custom parameter to set the split argument to at least be able to ignore such cases.

For example:
`class="payment-icon payment-methods-{{method.name | slugify}} {{method.provider_name | slugify}} {{payment.currentLocale.code.substr(0, 2)}} {{payment.transaction.type}}"`

can safely be supported with a RegEx split like this one `/\s+(?![^{]*})/` instead of the default `/\s+/`

### PR DESCRIPTION
**Pull request by alfaproject**
This is my proposal to close #157.

### CODE REVIEW

**Comment by alfaproject** [comment]
I've also updated `package.json` and `.travis.yml` to fix the minimum support of this module. The `gulp-eslint` version being used requires node 4 to be installed.

**Comment by mlochbaum** [comment]
Thanks for the `package.json` and `.travis.yml` fixes. I hadn't been able to figure out why Travis wasn't working.

This change needs to be combined with `id-class-ignore-regex`, which fixes the same problem for `id-class-style`. It might also be a good idea to combine it with `attr-name-ignore-regex` and the proposed `raw-ignore-regex` (issue #155) by just making some `extension-tag-regex` option that applies everywhere. I'm definitely willing to put off that change, though.

I think the way to proceed is to merge the `class-no-dup.js` rule into `class-style.js`, and then just use the existing `id-class-ignore-regex` option to control the duplication check as well. I want to keep the existing regex style (so that the simpler `{{.*?}}` is enough to ignore Angular tags), but I'm not sure if there's a performant way to use that for splitting.

**Comment by alfaproject** [comment]
But this way you are not ignoring. If you check the unit tests it actually checks interpolated values too as repeated (if they are). What you are suggesting will just ignore the whole value of the class which I don't think it's a good user experience ):

**Comment by mlochbaum** [comment]
Oops, I wasn't clear about that. `id-class-ignore-regex` should be used for splitting like in your PR, and then the split classes should matching the regex should be ignored for `id-class-style` but not for `class-no-dup`. The option could be renamed, but it still ignores for the purposes of `id-class-style` so it doesn't have to be.

**Comment by mlochbaum** [comment]
I have working code that uses `id-class-ignore-regex` and passes the tests you gave, plus one that checks that it does actually distinguish special tags from each other. I'll clean it up a bit and push in the morning.

**Comment by alfaproject** [comment]
Oh nice, let me know if I can help testing. I have a lot of Angular code that I can test with. (:

**Comment by mlochbaum** [comment]
Let me know if this works for you.

**Comment by alfaproject** [comment]
It works for me, but I'm up to unify this at some point if you are. ^_^

**Pull request merged**
